"""
S&P 500 companies data
This file contains all S&P 500 stock symbols and company names
"""

SP500_COMPANIES = [
    ("MMM", "3M Company"),
    ("ABT", "Abbott Laboratories"),
    ("ABBV", "AbbVie Inc."),
    ("ACN", "Accenture plc"),
    ("ADBE", "Adobe Inc."),
    ("AMD", "Advanced Micro Devices Inc."),
    ("AES", "AES Corporation"),
    ("AFL", "Aflac Incorporated"),
    ("A", "Agilent Technologies Inc."),
    ("APD", "Air Products and Chemicals Inc."),
    ("AKAM", "Akamai Technologies Inc."),
    ("ALB", "Albemarle Corporation"),
    ("ARE", "Alexandria Real Estate Equities Inc."),
    ("ALGN", "Align Technology Inc."),
    ("ALLE", "Allegion plc"),
    ("LNT", "Alliant Energy Corporation"),
    ("ALL", "Allstate Corporation"),
    ("GOOGL", "Alphabet Inc. Class A"),
    ("GOOG", "Alphabet Inc. Class C"),
    ("MO", "Altria Group Inc."),
    ("AMZN", "Amazon.com Inc."),
    ("AMCR", "Amcor plc"),
    ("AEE", "Ameren Corporation"),
    ("AAL", "American Airlines Group Inc."),
    ("AEP", "American Electric Power Company Inc."),
    ("AXP", "American Express Company"),
    ("AIG", "American International Group Inc."),
    ("AMT", "American Tower Corporation"),
    ("AWK", "American Water Works Company Inc."),
    ("AMP", "Ameriprise Financial Inc."),
    ("ABC", "AmerisourceBergen Corporation"),
    ("AME", "AMETEK Inc."),
    ("AMGN", "Amgen Inc."),
    ("APH", "Amphenol Corporation"),
    ("ADI", "Analog Devices Inc."),
    ("ANSS", "ANSYS Inc."),
    ("AON", "Aon plc"),
    ("APA", "APA Corporation"),
    ("AAPL", "Apple Inc."),
    ("AMAT", "Applied Materials Inc."),
    ("APTV", "Aptiv plc"),
    ("ANET", "Arista Networks Inc."),
    ("AJG", "Arthur J. Gallagher & Co."),
    ("AIZ", "Assurant Inc."),
    ("T", "AT&T Inc."),
    ("ATO", "Atmos Energy Corporation"),
    ("ADSK", "Autodesk Inc."),
    ("ADP", "Automatic Data Processing Inc."),
    ("AZO", "AutoZone Inc."),
    ("AVB", "AvalonBay Communities Inc."),
    ("AVY", "Avery Dennison Corporation"),
    ("BKR", "Baker Hughes Company"),
    ("BALL", "Ball Corporation"),
    ("BBWI", "Bath & Body Works Inc."),
    ("BAX", "Baxter International Inc."),
    ("BDX", "Becton Dickinson and Company"),
    ("BRK.B", "Berkshire Hathaway Inc. Class B"),
    ("BBY", "Best Buy Co. Inc."),
    ("BIO", "Bio-Rad Laboratories Inc."),
    ("TECH", "Bio-Techne Corporation"),
    ("BIIB", "Biogen Inc."),
    ("BLK", "BlackRock Inc."),
    ("BK", "Bank of New York Mellon Corporation"),
    ("BA", "Boeing Company"),
    ("BKNG", "Booking Holdings Inc."),
    ("BWA", "BorgWarner Inc."),
    ("BXP", "Boston Properties Inc."),
    ("BSX", "Boston Scientific Corporation"),
    ("BMY", "Bristol-Myers Squibb Company"),
    ("BR", "Broadridge Financial Solutions Inc."),
    ("BRO", "Brown & Brown Inc."),
    ("BLDR", "Builders FirstSource Inc."),
    ("BG", "Bunge Limited"),
    ("CDNS", "Cadence Design Systems Inc."),
    ("CZR", "Caesars Entertainment Inc."),
    ("CPT", "Camden Property Trust"),
    ("CPB", "Campbell Soup Company"),
    ("COF", "Capital One Financial Corporation"),
    ("CAH", "Cardinal Health Inc."),
    ("KMX", "CarMax Inc."),
    ("CCL", "Carnival Corporation"),
    ("CARR", "Carrier Global Corporation"),
    ("CAT", "Caterpillar Inc."),
    ("CBOE", "Cboe Global Markets Inc."),
    ("CBRE", "CBRE Group Inc."),
    ("CDW", "CDW Corporation"),
    ("CE", "Celanese Corporation"),
    ("CNC", "Centene Corporation"),
    ("CNP", "CenterPoint Energy Inc."),
    ("CDAY", "Ceridian HCM Holding Inc."),
    ("CF", "CF Industries Holdings Inc."),
    ("CRL", "Charles River Laboratories International Inc."),
    ("SCHW", "Charles Schwab Corporation"),
    ("CHTR", "Charter Communications Inc."),
    ("CVX", "Chevron Corporation"),
    ("CMG", "Chipotle Mexican Grill Inc."),
    ("CB", "Chubb Limited"),
    ("CHD", "Church & Dwight Co. Inc."),
    ("CI", "Cigna Corporation"),
    ("CINF", "Cincinnati Financial Corporation"),
    ("CTAS", "Cintas Corporation"),
    ("CSCO", "Cisco Systems Inc."),
    ("C", "Citigroup Inc."),
    ("CFG", "Citizens Financial Group Inc."),
    ("CLX", "Clorox Company"),
    ("CME", "CME Group Inc."),
    ("CMS", "CMS Energy Corporation"),
    ("KO", "Coca-Cola Company"),
    ("CTSH", "Cognizant Technology Solutions Corporation"),
    ("CL", "Colgate-Palmolive Company"),
    ("CMCSA", "Comcast Corporation"),
    ("CMA", "Comerica Incorporated"),
    ("CAG", "Conagra Brands Inc."),
    ("COP", "ConocoPhillips"),
    ("ED", "Consolidated Edison Inc."),
    ("STZ", "Constellation Brands Inc."),
    ("CEG", "Constellation Energy Corporation"),
    ("COO", "Cooper Companies Inc."),
    ("CPRT", "Copart Inc."),
    ("GLW", "Corning Incorporated"),
    ("CTVA", "Corteva Inc."),
    ("CSGP", "CoStar Group Inc."),
    ("COST", "Costco Wholesale Corporation"),
    ("CTRA", "Coterra Energy Inc."),
    ("CCI", "Crown Castle Inc."),
    ("CSX", "CSX Corporation"),
    ("CMI", "Cummins Inc."),
    ("CVS", "CVS Health Corporation"),
    ("DHI", "D.R. Horton Inc."),
    ("DHR", "Danaher Corporation"),
    ("DRI", "Darden Restaurants Inc."),
    ("DVA", "DaVita Inc."),
    ("DE", "Deere & Company"),
    ("DAL", "Delta Air Lines Inc."),
    ("XRAY", "Dentsply Sirona Inc."),
    ("DVN", "Devon Energy Corporation"),
    ("DXCM", "DexCom Inc."),
    ("FANG", "Diamondback Energy Inc."),
    ("DLR", "Digital Realty Trust Inc."),
    ("DFS", "Discover Financial Services"),
    ("DG", "Dollar General Corporation"),
    ("DLTR", "Dollar Tree Inc."),
    ("D", "Dominion Energy Inc."),
    ("DPZ", "Domino's Pizza Inc."),
    ("DOV", "Dover Corporation"),
    ("DOW", "Dow Inc."),
    ("DTE", "DTE Energy Company"),
    ("DUK", "Duke Energy Corporation"),
    ("DD", "DuPont de Nemours Inc."),
    ("DXC", "DXC Technology Company"),
    ("EMN", "Eastman Chemical Company"),
    ("ETN", "Eaton Corporation plc"),
    ("EBAY", "eBay Inc."),
    ("ECL", "Ecolab Inc."),
    ("EIX", "Edison International"),
    ("EW", "Edwards Lifesciences Corporation"),
    ("EA", "Electronic Arts Inc."),
    ("ELV", "Elevance Health Inc."),
    ("LLY", "Eli Lilly and Company"),
    ("EMR", "Emerson Electric Co."),
    ("ENPH", "Enphase Energy Inc."),
    ("ETR", "Entergy Corporation"),
    ("EOG", "EOG Resources Inc."),
    ("EPAM", "EPAM Systems Inc."),
    ("EQT", "EQT Corporation"),
    ("EFX", "Equifax Inc."),
    ("EQIX", "Equinix Inc."),
    ("EQR", "Equity Residential"),
    ("ESS", "Essex Property Trust Inc."),
    ("ETSY", "Etsy Inc."),
    ("EVRG", "Evergy Inc."),
    ("ES", "Eversource Energy"),
    ("EXC", "Exelon Corporation"),
    ("EXPE", "Expedia Group Inc."),
    ("EXPD", "Expeditors International of Washington Inc."),
    ("EXR", "Extra Space Storage Inc."),
    ("XOM", "Exxon Mobil Corporation"),
    ("FFIV", "F5 Inc."),
    ("FDS", "FactSet Research Systems Inc."),
    ("FICO", "Fair Isaac Corporation"),
    ("FAST", "Fastenal Company"),
    ("FRT", "Federal Realty Investment Trust"),
    ("FDX", "FedEx Corporation"),
    ("FIS", "Fidelity National Information Services Inc."),
    ("FITB", "Fifth Third Bancorp"),
    ("FE", "FirstEnergy Corp."),
    ("FISV", "Fiserv Inc."),
    ("FLT", "FleetCor Technologies Inc."),
    ("FMC", "FMC Corporation"),
    ("F", "Ford Motor Company"),
    ("FTNT", "Fortinet Inc."),
    ("FTV", "Fortive Corporation"),
    ("FOXA", "Fox Corporation Class A"),
    ("FOX", "Fox Corporation Class B"),
    ("BEN", "Franklin Resources Inc."),
    ("FCX", "Freeport-McMoRan Inc."),
    ("GRMN", "Garmin Ltd."),
    ("IT", "Gartner Inc."),
    ("GEHC", "GE HealthCare Technologies Inc."),
    ("GEN", "Gen Digital Inc."),
    ("GNRC", "Generac Holdings Inc."),
    ("GD", "General Dynamics Corporation"),
    ("GE", "General Electric Company"),
    ("GIS", "General Mills Inc."),
    ("GM", "General Motors Company"),
    ("GPC", "Genuine Parts Company"),
    ("GILD", "Gilead Sciences Inc."),
    ("GL", "Globe Life Inc."),
    ("GPN", "Global Payments Inc."),
    ("GS", "Goldman Sachs Group Inc."),
    ("HAL", "Halliburton Company"),
    ("HIG", "Hartford Financial Services Group Inc."),
    ("HAS", "Hasbro Inc."),
    ("HCA", "HCA Healthcare Inc."),
    ("HSIC", "Henry Schein Inc."),
    ("HSY", "Hershey Company"),
    ("HES", "Hess Corporation"),
    ("HPE", "Hewlett Packard Enterprise Company"),
    ("HLT", "Hilton Worldwide Holdings Inc."),
    ("HOLX", "Hologic Inc."),
    ("HD", "Home Depot Inc."),
    ("HON", "Honeywell International Inc."),
    ("HRL", "Hormel Foods Corporation"),
    ("HST", "Host Hotels & Resorts Inc."),
    ("HWM", "Howmet Aerospace Inc."),
    ("HPQ", "HP Inc."),
    ("HUM", "Humana Inc."),
    ("HBAN", "Huntington Bancshares Incorporated"),
    ("HII", "Huntington Ingalls Industries Inc."),
    ("IBM", "International Business Machines Corporation"),
    ("IEX", "IDEX Corporation"),
    ("IDXX", "IDEXX Laboratories Inc."),
    ("ITW", "Illinois Tool Works Inc."),
    ("ILMN", "Illumina Inc."),
    ("INCY", "Incyte Corporation"),
    ("IR", "Ingersoll Rand Inc."),
    ("INTC", "Intel Corporation"),
    ("ICE", "Intercontinental Exchange Inc."),
    ("IFF", "International Flavors & Fragrances Inc."),
    ("IP", "International Paper Company"),
    ("IPG", "Interpublic Group of Companies Inc."),
    ("INTU", "Intuit Inc."),
    ("ISRG", "Intuitive Surgical Inc."),
    ("IVZ", "Invesco Ltd."),
    ("INVH", "Invitation Homes Inc."),
    ("IQV", "IQVIA Holdings Inc."),
    ("IRM", "Iron Mountain Incorporated"),
    ("JBHT", "J.B. Hunt Transport Services Inc."),
    ("JKHY", "Jack Henry & Associates Inc."),
    ("J", "Jacobs Solutions Inc."),
    ("JNJ", "Johnson & Johnson"),
    ("JCI", "Johnson Controls International plc"),
    ("JPM", "JPMorgan Chase & Co."),
    ("JNPR", "Juniper Networks Inc."),
    ("K", "Kellogg Company"),
    ("KDP", "Keurig Dr Pepper Inc."),
    ("KEY", "KeyCorp"),
    ("KEYS", "Keysight Technologies Inc."),
    ("KMB", "Kimberly-Clark Corporation"),
    ("KIM", "Kimco Realty Corporation"),
    ("KMI", "Kinder Morgan Inc."),
    ("KLAC", "KLA Corporation"),
    ("KHC", "Kraft Heinz Company"),
    ("KR", "Kroger Company"),
    ("LHX", "L3Harris Technologies Inc."),
    ("LH", "Laboratory Corporation of America Holdings"),
    ("LVS", "Las Vegas Sands Corp."),
    ("LDOS", "Leidos Holdings Inc."),
    ("LEN", "Lennar Corporation"),
    ("LIN", "Linde plc"),
    ("LYV", "Live Nation Entertainment Inc."),
    ("LKQ", "LKQ Corporation"),
    ("LMT", "Lockheed Martin Corporation"),
    ("L", "Loews Corporation"),
    ("LOW", "Lowe's Companies Inc."),
    ("LULU", "Lululemon Athletica Inc."),
    ("LYB", "LyondellBasell Industries N.V."),
    ("MTB", "M&T Bank Corporation"),
    ("MRO", "Marathon Oil Corporation"),
    ("MPC", "Marathon Petroleum Corporation"),
    ("MKTX", "MarketAxess Holdings Inc."),
    ("MAR", "Marriott International Inc."),
    ("MMC", "Marsh & McLennan Companies Inc."),
    ("MLM", "Martin Marietta Materials Inc."),
    ("MAS", "Masco Corporation"),
    ("MA", "Mastercard Incorporated"),
    ("MTCH", "Match Group Inc."),
    ("MKC", "McCormick & Company Incorporated"),
    ("MCD", "McDonald's Corporation"),
    ("MCK", "McKesson Corporation"),
    ("MDT", "Medtronic plc"),
    ("MRK", "Merck & Co. Inc."),
    ("META", "Meta Platforms Inc."),
    ("MET", "MetLife Inc."),
    ("MTD", "Mettler-Toledo International Inc."),
    ("MGM", "MGM Resorts International"),
    ("MCHP", "Microchip Technology Incorporated"),
    ("MU", "Micron Technology Inc."),
    ("MSFT", "Microsoft Corporation"),
    ("MAA", "Mid-America Apartment Communities Inc."),
    ("MRNA", "Moderna Inc."),
    ("MHK", "Mohawk Industries Inc."),
    ("MOH", "Molina Healthcare Inc."),
    ("TAP", "Molson Coors Beverage Company"),
    ("MDLZ", "Mondelez International Inc."),
    ("MPWR", "Monolithic Power Systems Inc."),
    ("MNST", "Monster Beverage Corporation"),
    ("MCO", "Moody's Corporation"),
    ("MS", "Morgan Stanley"),
    ("MOS", "Mosaic Company"),
    ("MSI", "Motorola Solutions Inc."),
    ("MSCI", "MSCI Inc."),
    ("NDAQ", "Nasdaq Inc."),
    ("NFLX", "Netflix Inc."),
    ("NEE", "NextEra Energy Inc."),
    ("NKE", "Nike Inc."),
    ("NI", "NiSource Inc."),
    ("NDSN", "Nordson Corporation"),
    ("NSC", "Norfolk Southern Corporation"),
    ("NTRS", "Northern Trust Corporation"),
    ("NOC", "Northrop Grumman Corporation"),
    ("NCLH", "Norwegian Cruise Line Holdings Ltd."),
    ("NRG", "NRG Energy Inc."),
    ("NUE", "Nucor Corporation"),
    ("NVT", "nVent Electric plc"),
    ("NVR", "NVR Inc."),
    ("NXPI", "NXP Semiconductors N.V."),
    ("ORLY", "O'Reilly Automotive Inc."),
    ("OXY", "Occidental Petroleum Corporation"),
    ("ODFL", "Old Dominion Freight Line Inc."),
    ("OMC", "Omnicom Group Inc."),
    ("ON", "ON Semiconductor Corporation"),
    ("OGN", "Organon & Co."),
    ("OTIS", "Otis Worldwide Corporation"),
    ("PCAR", "PACCAR Inc."),
    ("PKG", "Packaging Corporation of America"),
    ("PANW", "Palo Alto Networks Inc."),
    ("PARA", "Paramount Global"),
    ("PH", "Parker-Hannifin Corporation"),
    ("PAYX", "Paychex Inc."),
    ("PAYC", "Paycom Software Inc."),
    ("PYPL", "PayPal Holdings Inc."),
    ("PENN", "Penn Entertainment Inc."),
    ("PNR", "Pentair plc"),
    ("PEP", "PepsiCo Inc."),
    ("PFE", "Pfizer Inc."),
    ("PCG", "PG&E Corporation"),
    ("PM", "Philip Morris International Inc."),
    ("PSX", "Phillips 66"),
    ("PNW", "Pinnacle West Capital Corporation"),
    ("PXD", "Pioneer Natural Resources Company"),
    ("PNC", "PNC Financial Services Group Inc."),
    ("POOL", "Pool Corporation"),
    ("PPG", "PPG Industries Inc."),
    ("PPL", "PPL Corporation"),
    ("PFG", "Principal Financial Group Inc."),
    ("PG", "Procter & Gamble Company"),
    ("PGR", "Progressive Corporation"),
    ("PLD", "Prologis Inc."),
    ("PRU", "Prudential Financial Inc."),
    ("PEG", "Public Service Enterprise Group Incorporated"),
    ("PTC", "PTC Inc."),
    ("PSA", "Public Storage"),
    ("PHM", "PulteGroup Inc."),
    ("QRVO", "Qorvo Inc."),
    ("PWR", "Quanta Services Inc."),
    ("QCOM", "QUALCOMM Incorporated"),
    ("DGX", "Quest Diagnostics Incorporated"),
    ("RL", "Ralph Lauren Corporation"),
    ("RJF", "Raymond James Financial Inc."),
    ("RTX", "RTX Corporation"),
    ("O", "Realty Income Corporation"),
    ("REG", "Regency Centers Corporation"),
    ("REGN", "Regeneron Pharmaceuticals Inc."),
    ("RF", "Regions Financial Corporation"),
    ("RSG", "Republic Services Inc."),
    ("RMD", "ResMed Inc."),
    ("RVTY", "Revvity Inc."),
    ("RHI", "Robert Half Inc."),
    ("ROK", "Rockwell Automation Inc."),
    ("ROL", "Rollins Inc."),
    ("ROP", "Roper Technologies Inc."),
    ("ROST", "Ross Stores Inc."),
    ("RCL", "Royal Caribbean Group"),
    ("SPGI", "S&P Global Inc."),
    ("SBAC", "SBA Communications Corporation"),
    ("SLB", "Schlumberger Limited"),
    ("SRE", "Sempra Energy"),
    ("NOW", "ServiceNow Inc."),
    ("SHW", "Sherwin-Williams Company"),
    ("SPG", "Simon Property Group Inc."),
    ("SWKS", "Skyworks Solutions Inc."),
    ("SJM", "J.M. Smucker Company"),
    ("SNA", "Snap-on Incorporated"),
    ("SEDG", "SolarEdge Technologies Inc."),
    ("SO", "Southern Company"),
    ("LUV", "Southwest Airlines Co."),
    ("SWK", "Stanley Black & Decker Inc."),
    ("SBUX", "Starbucks Corporation"),
    ("STT", "State Street Corporation"),
    ("STLD", "Steel Dynamics Inc."),
    ("STE", "STERIS plc"),
    ("SYK", "Stryker Corporation"),
    ("SIVB", "SVB Financial Group"),
    ("SYY", "Sysco Corporation"),
    ("TMUS", "T-Mobile US Inc."),
    ("TROW", "T. Rowe Price Group Inc."),
    ("TTWO", "Take-Two Interactive Software Inc."),
    ("TGT", "Target Corporation"),
    ("TEL", "TE Connectivity Ltd."),
    ("TDY", "Teledyne Technologies Incorporated"),
    ("TFX", "Teleflex Incorporated"),
    ("TER", "Teradyne Inc."),
    ("TSLA", "Tesla Inc."),
    ("TXN", "Texas Instruments Incorporated"),
    ("TXT", "Textron Inc."),
    ("TMO", "Thermo Fisher Scientific Inc."),
    ("TJX", "TJX Companies Inc."),
    ("TSCO", "Tractor Supply Company"),
    ("TT", "Trane Technologies plc"),
    ("TDG", "TransDigm Group Incorporated"),
    ("TRMB", "Trimble Inc."),
    ("TRV", "Travelers Companies Inc."),
    ("TRGP", "Targa Resources Corp."),
    ("TFC", "Truist Financial Corporation"),
    ("TYL", "Tyler Technologies Inc."),
    ("TSN", "Tyson Foods Inc."),
    ("USB", "U.S. Bancorp"),
    ("UDR", "UDR Inc."),
    ("ULTA", "Ulta Beauty Inc."),
    ("UNP", "Union Pacific Corporation"),
    ("UAL", "United Airlines Holdings Inc."),
    ("UPS", "United Parcel Service Inc."),
    ("URI", "United Rentals Inc."),
    ("UNH", "UnitedHealth Group Incorporated"),
    ("UAA", "Under Armour Inc. Class A"),
    ("UA", "Under Armour Inc. Class C"),
    ("VLO", "Valero Energy Corporation"),
    ("VTR", "Ventas Inc."),
    ("VRSN", "Verisign Inc."),
    ("VRSK", "Verisk Analytics Inc."),
    ("VZ", "Verizon Communications Inc."),
    ("VRTX", "Vertex Pharmaceuticals Incorporated"),
    ("VFC", "V.F. Corporation"),
    ("VICI", "Vici Properties Inc."),
    ("V", "Visa Inc."),
    ("VMC", "Vulcan Materials Company"),
    ("WAB", "Wabtec Corporation"),
    ("WBA", "Walgreens Boots Alliance Inc."),
    ("WMT", "Walmart Inc."),
    ("WBD", "Warner Bros. Discovery Inc."),
    ("WM", "Waste Management Inc."),
    ("WAT", "Waters Corporation"),
    ("WEC", "WEC Energy Group Inc."),
    ("WFC", "Wells Fargo & Company"),
    ("WELL", "Welltower Inc."),
    ("WST", "West Pharmaceutical Services Inc."),
    ("WY", "Weyerhaeuser Company"),
    ("WMB", "Williams Companies Inc."),
    ("WTW", "Willis Towers Watson Public Limited Company"),
    ("GWW", "W.W. Grainger Inc."),
    ("WYNN", "Wynn Resorts Limited"),
    ("XEL", "Xcel Energy Inc."),
    ("XYL", "Xylem Inc."),
    ("YUM", "Yum! Brands Inc."),
    ("ZBRA", "Zebra Technologies Corporation"),
    ("ZBH", "Zimmer Biomet Holdings Inc."),
    ("ZION", "Zions Bancorporation National Association"),
    ("ZTS", "Zoetis Inc.")
]

def get_sp500_companies():
    """Return list of S&P 500 companies as (symbol, name) tuples"""
    return SP500_COMPANIES